### ISSUE TITLE
MongooseError

### ISSUE THREAD

**Issue by hotsu0p** [Monochromish/Kalopsia-Bot#13]
MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.

Got this

**Comment by Monochromish** [comment]
there's an `example.env` file provided for guidance. it looks like mongoose is getting an undefined value, suggesting that the necessary uri isn't being passed. if you haven't already, rename the `example.env` file to simply `.env`. after that, modify it to have the necessary values. here's a template for reference:

```
MONGO_URI=mongodb://<username>:<password>@<host>:<port>/<database>
TOKEN=<discordBotToken>
```

make sure to replace the placeholders with your actual data. let me know if the error persists

**Comment by hotsu0p** [comment]
It keeps on not working. strange
