### ISSUE TITLE
Giveaway not working - options.winnerCount is not a positive integer. (val=4)

### ISSUE THREAD

**Issue by T0BiD** [Monochromish/Kalopsia-Bot#2]
Here's the line where you need to fix it:

https://github.com/Monochromish/Kalopsia-Bot/blob/ca643a966a9a8391d3c50f8232f82802c8cda6df/commands/Giveaway/start.js#L37

parseInt(giveawayNumberWinners)

**Comment by Monochromish** [comment]
ill look into this issue, thanks for reporting
